sudo: required
notifications:
  email: false
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=verifybuild/java8
  - secure: HcnAROgX+R9uyf4Osd/u0zsX1MZs+YhIM40CIUtCSjRn2U5oLiUAw04t0BCG0/Wv2RYQNZoPR9Kg5aT653pDmHZWBpP7HLJuEwhNT+pbd9iT3Ufc05H1YDtO/cuMRuslsJvLSfPBvzwbmvKPVEz/nw8Y2a7pKO9VBn5Qb6MnVw0/mzmDpZU8KOUooZChv0cRzaXTcmGSwFBLRtUq7kfSa03OnYsPByc5L8Ef0WThwaUnLt6n/XDLKLQl/1qJxjt7W/0xpTxErgDKtpJmsCefIpMevNA58GkeMAVYIqMqU+EWg/nnriT15LrZq1CYiouS7FAeiG1HptnczYbtuhpvS32Po6F5r6U5EG0vISACsI5HBGGGHWwg5PoxO171G5lgNqtcQ/jbQNhE4xU/nPjjqzc/L0HBJwN7T/p8QofOrpACMhiNkRCV7CBHF973xSgWns88pMFp4i3L3k7AEV1kZYMa2+oDaLCeMV6ECDuEoQDGVVKuI7zpfIkiWP/l1Q0rb295Ln8+O2bw1HNjm+z6moTSAdIUAkmEecaZyaS22twqXL4QyFh/BUhXq11ArDP3g7ciFhXMG6FTpI5h2d7DvFTKuRLHppG7/skZM3/GA1MwL9ieW2fclkjyRQPtwJ6c0+BRawGdxcAk3SuISKPkXRopsF68PzExVirJyb1mEC4=
  - secure: SBgA4wfBpMnEYpD8NcP/J3i9E7M48iw4K4tulScTC22VGTyZ72W9bHjD9JXizzUcOV59aOdDfYXYU5sIRbMYYA4xyt7K3TlUM8+kXPuHmpWwIj5FLs6FFkO1V00Meuyaon8I/HbzFWm1EF/PNYPPlew3PbIF5ZU4SRFHUqBdkpuq5EdkY/DqzV9D84cU8dhRna2pbDa1JXiCthocPa2S4eaHhIxtpZ9dL7UmEIhI1f+bGuH0PdUFVUDobYj0NPKXkhetqJOx4Rn8aONO8nfS+cYYmZDBaJbDvNjzGHvyY7ISpERGXbXXX0ThsShj+ix88g4bahUKXxRW7QkEAa5EoXhjxD8i0Rf023x/4527bAPL57vWtN1NKyZnqW0z26kv8rI8RncReRRI6+qHf4KLKQV1VYnsbsaw0KB3bRlQDda53EHnAN7JPMEwKR718ykHx/YYpPKYiaidPuaWGp12CO55VUxa9C7cMvn2X687iBteXqHlF/SWPxIELt4DER928fegE/q8KRLUsrcXqnIOJrKzf17X4KgRT4FXQojrg3+DWYN+VpEKd4hjzTFLYldlGSvM3XX/JDAQnzRhDNztQfmHWVLWkRwLayZSEij9WOb+ea1VZLlJNyTZBmtOeyjuTn9jZbn86jb9RWIUcPEK0dXvDYn6zJRzEyzfPog10rU=
before_install:
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
- export TAG=$(if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    echo "latest"
  else
    echo $TRAVIS_PULL_REQUEST_BRANCH
  fi)
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER
    docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
