sudo: required
notifications:
  email: false
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=verifybuild/java8
  - secure: HcnAROgX+R9uyf4Osd/u0zsX1MZs+YhIM40CIUtCSjRn2U5oLiUAw04t0BCG0/Wv2RYQNZoPR9Kg5aT653pDmHZWBpP7HLJuEwhNT+pbd9iT3Ufc05H1YDtO/cuMRuslsJvLSfPBvzwbmvKPVEz/nw8Y2a7pKO9VBn5Qb6MnVw0/mzmDpZU8KOUooZChv0cRzaXTcmGSwFBLRtUq7kfSa03OnYsPByc5L8Ef0WThwaUnLt6n/XDLKLQl/1qJxjt7W/0xpTxErgDKtpJmsCefIpMevNA58GkeMAVYIqMqU+EWg/nnriT15LrZq1CYiouS7FAeiG1HptnczYbtuhpvS32Po6F5r6U5EG0vISACsI5HBGGGHWwg5PoxO171G5lgNqtcQ/jbQNhE4xU/nPjjqzc/L0HBJwN7T/p8QofOrpACMhiNkRCV7CBHF973xSgWns88pMFp4i3L3k7AEV1kZYMa2+oDaLCeMV6ECDuEoQDGVVKuI7zpfIkiWP/l1Q0rb295Ln8+O2bw1HNjm+z6moTSAdIUAkmEecaZyaS22twqXL4QyFh/BUhXq11ArDP3g7ciFhXMG6FTpI5h2d7DvFTKuRLHppG7/skZM3/GA1MwL9ieW2fclkjyRQPtwJ6c0+BRawGdxcAk3SuISKPkXRopsF68PzExVirJyb1mEC4=
  - secure: hch7OUbdxqd4mY4qmbpIpiayAHlNsy6cygn/qdtqrHuW8LilUuEu3lvWiN+f1YQTHuPyJjOWmMrCVJG/432CP59O4WbLVTwda+IYXkYD0apdJ9NB2i42BKGMKUblUSw7oorzZy5bhYb8tEaXoESJCoj6qYzvO6IdC30/wxuxeP1S/RfiWrljkE5qlpc9FRU9YBaZ1bcnA9gLpB92eCYKz+U++5nWWZhR9c/3Lhz/wBqqvb/RyQNuEK+8cFp58zUkJ3re9C+2k1K5bYw1ckWEw3USCEOqybcc0ZboUWM454hxo42LicZHsElofMXS6HNTtLiW+4fZq/ooqcAlW1FfnrIzVLYeZFh2BaSHHcclvXepJj230fTJEmZ39zqHdZ+s3AezbnCnxqlA+nzEqLBkjAGV4bntY2OLxeOSkVyG/YC8VerKdDCu2TAIpqlqPqrDqqHCmER4Wn1+aaLJGI+bcQA90HPf9agircyluAkTkyuEQSZ1aBZQiQi0Yns3Vs6MPE3irh8fN85u0Br0+mYq17NaZ+lzx7m2GE4FVOFFryGfEFgisGKftqQfIOZJkSmfEuPSUepLucjGPR+7kDZKQJW+z7kpXssU33BV/f8KnuPqu8R2pGpq0/IDvVCSTTn5FHHc61iw7bwf0eTn669Zi3/MCT3aR6wRv1ZddPnt40A=
before_install:
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
- export TAG=$(if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    echo "latest";
  else
    echo $TRAVIS_PULL_REQUEST_BRANCH;
  fi)
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER
    docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
